<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MDaftarAlasanHukumanDisiplinSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $data = [
      ['id'=>1, 'nama'=>'TIDAK MENGUCAPKAN SUMPAH/JANJI PNS'],
      ['id'=>2, 'nama'=>'TIDAK MENGUCAPKAN SUMPAH/JANJI JABATAN'],
      ['id'=>3, 'nama'=>'TIDAK SETIA DAN TAAT SEPENUHNYA KEPADA PANCASILA, UNDANG-UNDANG DASAR NEGARA REPUPLIK INDONESIA TAHUN 1945, NEGARA KESATUAN REPUBLIK INDONESIA, DAN PEMERINTAH '],
      ['id'=>4, 'nama'=>'TIDAK MENAATI SEGALA KETENTUAN PERATURAN PERUNDANGUNDANGAN'],
      ['id'=>5, 'nama'=>'TIDAK MELAKSANAKAN TUGAS KEDINASAN YANG DIPERCAYAKAN KEPADA PNS DENGAN PENUH PENGABDIAN, KESADARAN, DAN TANGGUNG JAWAB'],
      ['id'=>6, 'nama'=>'TIDAK MENJUNJUNG TINGGI KEHORMATAN NEGARA, PEMERINTAH, DAN MARTABAT PNS'],
      ['id'=>7, 'nama'=>'TIDAK MENGUTAMAKAN KEPENTINGAN NEGARA DARIPADA KEPENTINGAN SENDIRI, SESEORANG,DAN/ATAU GOLONGAN'],
      ['id'=>8, 'nama'=>'TIDAK MEMEGANG RAHASIA JABATAN YANG MENURUT SIFATNYA ATAU MENURUT PERINTAH HARUS DIRAHASIAKAN'],
      ['id'=>9, 'nama'=>'TIDAK BEKERJA DENGAN JUJUR, TERTIB, CERMAT, DAN BERSEMANGAT UNTUK KEPENTINGAN NEGARA'],
      ['id'=>10, 'nama'=>'TIDAK MELAPORKAN DENGAN SEGERA KEPADA ATASANNYA APABILA MENGETAHUI ADA HAL YANG DAPAT MEMBAHAYAKAN ATAU MERUGIKAN NEGARA ATAU PEMERINTAH TERUTAMA DI BIDANG KEAMANAN, KEUANGAN, DAN MATERIIL'],
      ['id'=>11, 'nama'=>'TIDAK MASUK KERJA DAN MENAATI KETENTUAN JAM KERJA'],
      ['id'=>12, 'nama'=>'TIDAK MENCAPAI SASARAN KERJA PEGAWAI YANG DITETAPKAN'],
      ['id'=>13, 'nama'=>'TIDAK MENGGUNAKAN DAN MEMELIHARA BARANG-BARANG MILIK NEGARA DENGAN SEBAIK-BAIKNYA'],
      ['id'=>14, 'nama'=>'TIDAK MEMBERIKAN PELAYANAN SEBAIK-BAIKNYA KEPADA MASYARAKAT'],
      ['id'=>15, 'nama'=>'TIDAK MEMBIMBING BAWAHAN DALAM MELAKSANAKAN TUGAS'],
      ['id'=>16, 'nama'=>'TIDAK MEMBERIKAN KESEMPATAN KEPADA BAWAHAN UNTUK MENGEMBANGKAN KARIER DAN;'],
      ['id'=>17, 'nama'=>'TIDAK MENAATI PERATURAN KEDINASAN YANG DITETAPKAN OLEH PEJABAT YANG BERWENANG.'],
      ['id'=>18, 'nama'=>'MENYALAHGUNAKAN WEWENANG'],
      ['id'=>19, 'nama'=>'MENJADI PERANTARA UNTUK MENDAPATKAN KEUNTUNGAN PRIBADI DAN/ ATAU ORANG LAIN DENGAN MENGGUNAKAN KEWENANGAN ORANG LAIN'],
      ['id'=>20, 'nama'=>'TANPA IZIN PEMERINTAH MENJADI PEGAWAI ATAU BEKERJA UNTUK NEGARA LAIN DAN/ ATAU LEMBAGA ATAU ORGANISASI INTERNASIONAL'],
      ['id'=>21, 'nama'=>'BEKERJA PADA PERUSAHAAN ASING, KONSULTAN ASING, ATAU LEMBAGA SWADAYA MASYARAKAT ASING'],
      ['id'=>22, 'nama'=>'MEMILIKI, MENJUAL, MEMBELI, MENGGADAIKAN, MENYEWAKAN, ATAU MEMINJAMKAN BARANG-BARANG BAIK BERGERAK ATAU TIDAK BERGERAK, DOKUMEN ATAU SURAT BERHARGA MILIK NEGARA SECARA TIDAK SAH'],
      ['id'=>23, 'nama'=>'MELAKUKAN KEGIATAN BERSAMA DENGAN ATASAN, TEMAN SEJAWAT, BAWAHAN, ATAU ORANG LAIN DI DALAM MAUPUN DI LUAR LINGKUNGAN KERJANYA DENGAN TUJUAN UNTUK KEUNTUNGAN PRIBADI, GOLONGAN, ATAU PIHAK LAIN, YANG SECARA LANGSUNG ATAU TIDAK LANGSUNG MERUGIKAN NEGARA'],
      ['id'=>24, 'nama'=>'MEMBERI ATAU MENYANGGUPI AKAN MEMBERI SESUATU KEPADA SIAPAPUN BAIK SECARA LANGSUNG ATAU TIDAK LANGSUNG DAN DENGAN DALIH APAPUN UNTUK DIANGKAT DALAM JABATAN'],
      ['id'=>25, 'nama'=>'MENERIMA HADIAH ATAU SESUATU PEMBERIAN APA SAJA DARI SIAPAPUN JUGA YANG BERHUBUNGAN DENGAN JABATAN DAN/ ATAU PEKERJAANNYA'],
      ['id'=>26, 'nama'=>'BERTINDAK SEWENANG-WENANG TERHADAP BAWAHANNYA'],
      ['id'=>27, 'nama'=>'MELAKUKAN SUATU TINDAKAN ATAU TIDAK MELAKUKAN SUATU TINDAKAN YANG DAPAT MENGHALANGI ATAU MEMPERSULIT SALAH SATU PIHAK YANG DILAYANI SEHINGGA MENGAKIBATKAN KERUGIAN BAGI YANG DILAYANI'],
      ['id'=>28, 'nama'=>'MENGHALANGI BERJALANNYA TUGAS KEDINASAN'],
      ['id'=>29, 'nama'=>'IKUT SERTA SEBAGAI PELAKSANA KAMPANYE'],
      ['id'=>30, 'nama'=>'MENJADI PESERTA KAMPANYE DENGAN MENGGUNAKAN ATRIBUT PARTAI ATAU ATRIBUT PNS'],
      ['id'=>31, 'nama'=>'SEBAGAI PESERTA KAMPANYE DENGAN MENGERAHKAN PNS LAIN; DAN/ATAU SEBAGAI PESERTA KAMPANYE DENGAN MENGGUNAKAN FASILITAS NEGARA'],
      ['id'=>32, 'nama'=>'MEMBUAT KEPUTUSAN DAN/ATAU TINDAKAN YANG MENGUNTUNGKAN ATAU MERUGIKAN SALAH SATU PASANGAN CALON SELAMA MASA KAMPANYE'],
      ['id'=>33, 'nama'=>'MENGADAKAN KEGIATAN YANG MENGARAH KEPADA KEPERPIHAKAN TERHADAP PASANGAN CALON YANG MENJADI PESERTA PEMILU SEBELUM, SELAMA, DAN SESUDAH MASA KAMPANYE MELIPUTI PERTEMUAN, AJAKAN, HIMBAUAN, SERUAN, ATAU PEMBERIAN BARANG KEPADA PNS DALAM LINGKUNGAN UNIT KERJANYA, ANGGOTA KELUARGA, DAN MASYARAKAT'],
      ['id'=>34, 'nama'=>'MELAKUKAN KEGIATAN BEPERGIAN KE LUAR DAERAH DAN/ATAU KEGIATAN MUDIK TMT 30 MARET 2020 ATAU PADA SAAT DITERBITKANNYA SE MENPAN RB NOMOR 36 TAHUN 2020 SESUAI DENGAN SE BKN NO 11/SE/IV/2020 (KATEGORI I)'],
      ['id'=>35, 'nama'=>'MELAKUKAN KEGIATAN BEPERGIAN KE LUAR DAERAH DAN/ATAU KEGIATAN MUDIK TMT 6 APRIL 2020 ATAU PADA SAAT DITERBITKANNYA SE MENPAN RB NOMOR 41 TAHUN 2020 SESUAI DENGAN SE BKN NO 11/SE/IV/2020 (KATEGORI II)'],
      ['id'=>36, 'nama'=>'MELAKUKAN KEGIATAN BEPERGIAN KE LUAR DAERAH DAN/ATAU KEGIATAN MUDIK TMT 9 APRIL 2020 ATAU PADA SAAT DITERBITKANNYA SE MENPAN RB NOMOR 46 TAHUN 2020 SESUAI DENGAN SE BKN NO 11/SE/IV/2020 (KATEGORI III)'],
      ['id'=>37, 'nama'=>'MELAKUKAN TINDAK PIDANA'],
      ['id'=>38, 'nama'=>'MENGGUNAKAN ATAU MENGEDARKAN NARKOBA'],
    ];

    foreach ($data as $key => $value) {
      DB::table('m_daftar_alasan_hukuman_disiplin')->insert([
        'id' => $value['id'],
        'nama' => $value['nama'],
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
        'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
      ]);
    }
  }
}
